--
-- PostgreSQL database dump
--

-- Dumped from database version 13.8
-- Dumped by pg_dump version 13.8

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: measurement; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.measurement (
    id integer NOT NULL,
    sensor_id integer,
    value real NOT NULL,
    raining boolean NOT NULL,
    created_at timestamp without time zone,
    CONSTRAINT measurement_value_check CHECK (((value > ('-100'::integer)::double precision) AND (value < (100)::double precision)))
);


ALTER TABLE public.measurement OWNER TO postgres;

--
-- Name: measurement_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.measurement ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.measurement_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: sensor; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.sensor (
    id integer NOT NULL,
    name character varying NOT NULL
);


ALTER TABLE public.sensor OWNER TO postgres;

--
-- Name: sensor_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.sensor ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.sensor_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: measurement; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.measurement (id, sensor_id, value, raining, created_at) FROM stdin;
4	2	26	f	2023-01-14 18:24:17.424914
5	3	35	t	2023-01-15 17:17:32.033323
6	3	45	f	2023-01-15 17:25:43.800813
7	3	45	t	2023-01-15 17:26:03.395322
8	4	3	t	2023-01-15 17:26:24.914188
9	4	3	f	2023-01-15 17:26:31.066865
3063	2	43	f	2023-01-17 13:31:32.99846
2	2	10	t	2023-01-14 17:49:36.763052
3	2	22	t	2023-01-14 18:22:02.611316
1	2	-9.3	t	2023-01-10 00:00:00
10	4	12	t	2023-01-15 18:10:47.582969
11	4	22	t	2023-01-15 18:14:44.201481
12	11	68	f	2023-01-16 16:43:11.416553
3064	10	88	f	2023-03-10 19:17:55.082966
3068	10	20.3	f	2023-03-11 13:38:58.792299
16	11	18	f	2023-01-16 16:43:11.804352
17	11	86	t	2023-01-16 16:43:11.815164
18	11	-45	f	2023-01-16 16:43:11.823015
19	11	-8	t	2023-01-16 16:43:11.831482
20	11	39	f	2023-01-16 16:43:11.838944
21	11	-59	t	2023-01-16 16:43:11.863055
23	12	-93	f	2023-01-16 16:47:50.936997
24	12	90	t	2023-01-16 16:47:50.947968
25	12	-91	t	2023-01-16 16:47:50.956024
26	12	-68	f	2023-01-16 16:47:50.964075
27	12	-47	f	2023-01-16 16:47:50.972125
28	12	71	f	2023-01-16 16:47:50.981245
29	12	-75	f	2023-01-16 16:47:50.988226
30	12	-77	t	2023-01-16 16:47:50.996278
31	12	-13	f	2023-01-16 16:47:51.004331
32	12	83	f	2023-01-16 16:47:51.013431
33	12	-41	f	2023-01-16 16:47:51.020542
34	12	-81	f	2023-01-16 16:47:51.029519
35	12	-37	f	2023-01-16 16:47:51.036566
36	12	21	t	2023-01-16 16:47:51.044636
37	12	45	f	2023-01-16 16:47:51.053679
38	12	31	f	2023-01-16 16:47:51.062788
39	12	57	f	2023-01-16 16:47:51.07087
40	12	-43	f	2023-01-16 16:47:51.078849
41	12	-96	t	2023-01-16 16:47:51.096931
42	12	43	t	2023-01-16 16:47:51.104064
43	12	-78	t	2023-01-16 16:47:51.121298
44	12	-19	f	2023-01-16 16:47:51.131382
45	12	23	t	2023-01-16 16:47:51.141435
46	12	-66	t	2023-01-16 16:47:51.155527
47	12	-79	t	2023-01-16 16:47:51.171486
48	12	57	t	2023-01-16 16:47:51.185446
49	12	53	t	2023-01-16 16:47:51.193556
50	12	-42	t	2023-01-16 16:47:51.203671
51	12	-31	f	2023-01-16 16:47:51.288068
52	12	-2	f	2023-01-16 16:47:51.328257
53	12	-25	f	2023-01-16 16:47:51.335333
54	12	-54	t	2023-01-16 16:47:51.345462
55	12	31	t	2023-01-16 16:47:51.35224
56	12	-35	t	2023-01-16 16:47:51.360374
57	12	27	f	2023-01-16 16:47:51.36838
58	12	-53	t	2023-01-16 16:47:51.377243
3065	10	88	f	2023-03-10 19:21:22.984364
3066	10	88	f	2023-03-10 19:23:21.725695
3067	10	69	f	2023-03-10 19:33:25.879164
3061	2	22	t	2023-01-16 17:55:08.815606
3062	2	43	f	2023-01-16 18:11:35.277146
\.


--
-- Data for Name: sensor; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.sensor (id, name) FROM stdin;
1	GlebSeonsor
2	GlebSensor
3	SergeySensor
4	IlyaSensor
5	weatherSensor
6	Vlad sensor
7	Olena sensor
8	Vova sensor
9	Olesia sensor
10	Ignat Sensor
11	Aleksandr Sensor
12	Denis Sensor
13	Elena Sensor
14	Edik Sensor
15	Arcadiy Sensor
\.


--
-- Name: measurement_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.measurement_id_seq', 3068, true);


--
-- Name: sensor_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.sensor_id_seq', 15, true);


--
-- Name: measurement measurement_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.measurement
    ADD CONSTRAINT measurement_pkey PRIMARY KEY (id);


--
-- Name: sensor sensor_name_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.sensor
    ADD CONSTRAINT sensor_name_key UNIQUE (name);


--
-- Name: sensor sensor_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.sensor
    ADD CONSTRAINT sensor_pkey PRIMARY KEY (id);


--
-- Name: measurement measurement_sensor_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.measurement
    ADD CONSTRAINT measurement_sensor_id_fkey FOREIGN KEY (sensor_id) REFERENCES public.sensor(id) ON DELETE CASCADE;


--
-- PostgreSQL database dump complete
--

